<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAll()
    {
        return $this->findAll();
    }

    public function getById(int $id)
    {
        return $this->find($id);
    }
}
